from flask import Blueprint, request, jsonify
from typing import Literal, Optional, Union, Annotated
from pydantic import BaseModel, Field, ValidationError, TypeAdapter

# --- types ---


class Subpart(BaseModel):
    label: str
    marks: int
    text: str


class QuestionAsset(BaseModel):
    id: Optional[str] = None
    kind: Literal["diagram", "stimulus", "graph", "table", "image", "pdf_page"]

    filename: str
    content_type: str
    size_bytes: Optional[int] = None

    page: Optional[int] = None
    description: Optional[str] = None
    alt_text: Optional[str] = None

    # This is generated by your backend.
    url: Optional[str] = None


class BaseQuestion(BaseModel):
    id: Optional[str] = None

    paper_id: str
    question_number: int
    kind: str

    text: str
    marks: int

    page_start: int
    page_end: Optional[int] = None

    topic: Optional[str] = None
    syllabus_area: Optional[str] = None
    tags: list[str] = Field(default_factory=list)

    subparts: list[Subpart] = Field(default_factory=list)
    assets: list[QuestionAsset] = Field(default_factory=list)

    answer: Optional[str] = None
    working_solution: Optional[str] = None


class MultipleChoiceQuestion(BaseQuestion):
    kind: Literal["multiple_choice"] = "multiple_choice"
    marks: int = 1

    options: dict[Literal["A", "B", "C", "D"], str]
    correct_option: Optional[Literal["A", "B", "C", "D"]] = None


class ShortAnswerQuestion(BaseQuestion):
    kind: Literal["short_answer"] = "short_answer"


class ExtendedResponseQuestion(BaseQuestion):
    kind: Literal["extended_response"] = "extended_response"


Question = Annotated[
    Union[
        MultipleChoiceQuestion,
        ShortAnswerQuestion,
        ExtendedResponseQuestion,
    ],
    Field(discriminator="kind"),
]


QuestionAdapter = TypeAdapter(Question)

# --- api ---

q_bp = Blueprint("tppr-questions-access", __name__)


@q_bp.route("/api/questions/upload", methods=["POST"])
def upload_question():
    data = request.get_json(silent=True)

    if data is None:
        return jsonify(
            {
                "error": "invalid_json",
                "message": "Request body must be valid JSON.",
            }
        ), 400

    try:
        question = QuestionAdapter.validate_python(data)
    except ValidationError as err:
        return jsonify(
            {
                "error": "validation_error",
                "message": "Question format is invalid.",
                "details": err.errors(),
            }
        ), 400

    return jsonify(
        {
            "message": "Question validated successfully.",
            "question_type": question.kind,
            "question": question.model_dump(mode="json"),
        }
    ), 200
